var frases = [ { phrase:
  "'1. Amor eterno' En este momento alguien te envía su amor, la primero persona que se te venga a tu mente es aquella que sostiene estos pensamientos amorosos acerca de ti. Posiblemente has estado preocupado por una relación y esto simboliza la confirmación del Arcángel Miguel de que todo está bien. Los ángeles cuidan de tu ser amado y te ayudan con tus relaciones.  Posibles significados: Encontrarás a tu alma gemela. Tu ser querido te envía un ‘’te amo’’ desde el cielo. Dios y los ángeles te aman. Date cuenta de que eres una persona capaz de ser amada aun cuando alguien te demuestre lo contrario. Un antiguo amor regresará a tu vida. Oración: Ayúdame a percibir todo el amor que me rodea para sentirme seguro al recibir, expresar y dar amor." },
{ phrase:
  "'2. Analiza tus opciones' Has trabajado muy duro para aceptar las circunstancias, ahora es tiempo de buscar alternativas. Tu forma de competir y adaptarte es admirable; aunque El Arcángel Miguel te recuerda que siempre es importante ser honesto y auténtico con uno mismo. No necesitas comprometerte de ninguna manera, ya que Miguel se asegurará de que tus necesidades estén satisfechas de una forma gentil y cariñosa. Posibles significados: Actualiza tu currículum y busca un nuevo empleo. Confía en que no estarás solo si terminas una relación enfermiza. Busca formas nuevas para sanar tu situación actual. Cambia al profesional con quien trabajas (Doctor, terapeuta, abogado etc.) Permítete soñar despierto acerca de tus opciones. Recuerda que todo es posible. Oración: Dios, gracias por tu sabiduría y amor al permitirme ver, entender y evaluar todas mis alternativas. Por favor guíame por el mejor camino hacia mi salud, mi felicidad y mi misión de vida." },
{ phrase:
  "'3. Los Ángeles del Romance te están ayudando' Las oraciones acerca de tu vida amorosa han sido escuchadas y respondidas. Existe un grupo de seres etéreos llamados Ángeles del Romance  que específicamente se enfocan en situaciones del corazón. Estos Ángeles te están dando la guía intuitiva, preparándote para el gran amor. Para manifestar las cualidades que deseas en tu pareja. Es probable que los Ángeles del Romance te pidan hacer cambios saludables en tu forma de vida; enfócate en la auto-mejora; aprende hobbies interesantes; haz amigos nuevos. Mientras más escuches tu intuición, tus oraciones de manifestar una relación amorosa serán respondidas de manera más rápida. Posibles significados: La persona por la que preguntas es tu alma gemela. Experimentarás un cambio positivo en tu relación actual. Estás aprendiendo a amarte a ti mismo. Sigue los consejos, pronto conocerás a alguien especial. Escucha tu intuición con respecto al ejercicio, dietas y otros aspectos de mejoramiento personal. Oración: Ángeles Guardianes de mi alma gemela, gracias por prepararla a ella y a mí para el amor, por motivarnos a hacer cambios desde el corazón, y por darnos la oportunidad de conocernos. Gracias por ayudarnos a reconocernos y a tener el valor de decir ‘’Hola’’ y con el tiempo desarrollar una verdadera relación íntima." },
{ phrase:
  "'4. Apóyate en Dios y los Ángeles' Eres una persona fuerte e independiente, aunque hay ocasiones en que todos necesitamos apoyo, y para ti éste es el momento. Esta carta  te aconseja que dejes la situación completamente en manos de Dios y los Ángeles. Si intentas solucionarlo solo, estarás generándote cargas innecesarias que te bloquearán el camino a la solución. ¡Te fortaleces cuando permites que los demás te ayuden y te apoyen! Posibles significados: Contrata más personal. Si te ofrecen más ayuda acéptala. Pide ayuda a tu familia y amigos. Consulta un terapeuta con el que puedas hablar libremente – y revisar- tus sentimientos. Oración: Dios, ángeles les entrego (describe la situación) ahora y por completo, me hago a un lado, y permito que los milagros brillen sobre todo y todos los involucrados." },
{ phrase:
  "'5. Comprométete '  Miguel te aconseja que te comprometas completamente con el resultado que esperas. Si tienes dudas o inseguridades sobre lo que mereces o vales el resultado final no será satisfactorio, pero al comprometerte iniciarás el movimiento del cambio en tu vida.  Posibles significados: Comprométete con tu relación actual para crear una atmósfera íntima y satisfactoria. Permítete disfrutar cada momento. Sumérgete en un proyecto interesante. Si eres músico o artista sé plenamente consciente de cada nota o de cada pincelada. Ten confianza cuando  escribas y hables. Oración: Arcángel Miguel, como Ángel del valor y la confianza te pido me prestes tu fuerza, me permitas comprometerme conmigo, con mi vida y mi misión divina, aconséjame para abrir mi corazón completamente a cada experiencia." },
{ phrase:
  "'6. Cree y confía' Para resolver esta situación debes creer que todo está resuelto y completo en este momento. A medida que tu fe crece, la puerta hacia soluciones divinas se abrirá. Tu confianza le permite a tu mente y a tu cuerpo relajarse, lo que incrementa tu fuerza y tu energía creativa, cualidades de gran ayuda para ti. Posibles significados: Esta situación tendrá un resultado satisfactorio. El pensar positivo traerá consigo el resultado deseado con mayor rapidez. Entrega tus preocupaciones a Dios y los ángeles. Confía en la persona sobre la cual preguntaste. ¡Cree en ti! Oración: Antes de irte a dormir por la noche, di: ‘’Arcángel Miguel, entra en mis sueños y reemplaza el miedo con fe y confianza. Lléname de fuerza, valor y seguridad." },
{ phrase:
  "'7. Cuidado y protegido' El Arcángel Miguel te protege en esta situación, así como en todo lo referente a tu vida. Tú y el Arcángel son un equipo: Sigue los consejos que te provee a través de tu intuición. Posiblemente sacaste esta carta porque estás pasando por un cambio significativo en tu vida y te sientes vulnerable, este es un símbolo para recordarte que Miguel te está cuidando 24 horas al día.  Esta carta también te invita a bajar la guardia en tus relaciones con las personas y los Ángeles. Abre tu corazón para dar y recibir amor y así podrás experimentar la intimidad que tanto deseas. Sé auténtico con los demás y cuéntales tus sentimientos a los Ángeles. Esto permite que otros te conozcan, te apoyen y te amen… y amarte a ti mismo por lo que eres. Posibles significados: Tus necesidades financieras serán cubiertas. Tendrás un resultado favorable en un asunto legal. Duerme tranquilo, tu hogar está bien cuidado. Tus hijos están protegidos y a salvo. Tus seres queridos están con los Ángeles en el cielo. Oración: Gracias por protegerme a mí y a mis seres queridos, asegurándose de que estamos a salvo y que todas nuestras necesidades están cubiertas. Acepto agradecida y agraciadamente su ayuda, sabiendo que es correcto para mí y otros aceptar ayuda celestial." },
{ phrase:
  "'8. Decide ser feliz' Los ángeles te han escuchado y responden a tus oraciones, en vez de basar tu felicidad en acontecimientos futuros, decide ser feliz ahora. La forma de hacerla es enfocándote en todo y todos aquellos por los que te sientes agradecido. ¿Qué es lo que funciona en tu vida? ¿Cuáles son tus bendiciones y tus puntos fuertes? Permitirte sentir alegría y placer te fortalece, toma el control de tu vida y evita que las influencias externas determinen tus sentimientos. Posibles significados: Deslígate del drama. Espera un milagro. Enlista tus agradecimientos. Mantén pensamientos positivos acerca de esta situación. Abre tu corazón al amor. Oración: Gracias por ayudarme a abrir mi corazón a la dicha, a la alegría y a la felicidad. Estoy dispuesto a ver todo lo bueno en mi vida. " },
{ phrase:
  "'9. Deslígate de la situación ' Te has involucrado tanto en una situación, hasta el punto de no poderla ver objetivamente. Esta carta te indica que es momento de dar un paso hacia atrás para obtener una vista más amplia de esta situación. El arcángel Miguel te pide te desprendas de las emociones que te rodean, así como a no tomar personal dicha experiencia, para así evitar ser afectado por el comportamiento de terceros, reemplazando acciones defensivas por acciones que contengan amor y sabiduría. Él te ayudará. Tómate un tiempo libre, lejos de las personas involucradas, no necesitas saber la solución inmediatamente, los ángeles están acargo de los detalles. Lo más importante es la paz interior, sentimiento que te guiará a nuevos y útiles descubrimientos. Posibles significados: No te metas en problemas de terceros –déjalos que los resuelvan entre ellos. Sé compasivo sin cargar con los problemas de los demás. Pide a Miguel que limpie tu energía. Es tiempo de dejar esa situación o relación enfermiza. Oración: Arcángel Miguel, te pido utilices tu flamante espada para cortar cualquier cordón conectado con el miedo y el drama para poder centrarme en la afirmación de que la paz está en mí y en esta situación." },
{ phrase:
  "'10. Dios está a cargo' Si, Dios está a cargo, ocupándose de todos los detalles. Dale a Dios todas tus preocupaciones y deja de luchar contra la corriente. Esta situación está tomando su curso natural y esimportante que confíes en que todas las cosas van por buen camino… Porque así es. Posibles significados: Pide ayuda y permítete recibirla cuando te sea ofrecida. Tus oraciones han sido escuchadas y respondidas. La solución milagrosa ya está en proceso. Disfruta la vida porque Dios se está haciendo cargo de los problemas. Oración: Dios ayúdame a soltar esta situación, dejándola ir para su resolución y sanación de todo y todos los involucrados con fe y confianza en tu sabiduría divina y amor infinito." },
{ phrase:
  "'11. Enfócate en tu meta' El Arcángel Miguel te está aconsejando durante el camino hacia tu propósito de vida. ¿Sientes emoción cada vez que piensas en la actividad u ocupación de tus sueños? Ésta es la señal de que vas por el camino correcto. Esta carta te recuerda que no hay que perder de vista tus metas. Visualiza continuamente que ya tienes la carrera o trabajo voluntario de tus sueños. Visualízate ayudando a los demás o resolviendo situaciones cercanas a tu corazón. Imagina que tienes seguridad financiera mientras te dedicas devotamente a esta actividad. Cualquier deseo es viable, siempre y cuando te mantengas enfocado en él. El camino para hacer realidad tus sueños puede ser diferente a tus expectativas, pero el resultado las excederá. Los Ángeles caminan a tu lado todo el tiempo. Mantén la fe… y sigue adelante! Oración: Gracias Arcángel Miguel por tu ayuda para enfocarme en mis intenciones y deseos. Te pido me ayudes a liberarme de dudas y miedos, otorgándome la confianza y el valor para tomar acción hacia la conquista de mis sueños." },
{ phrase:
  "'12. Enfócate en una salud perfecta y divina' El Arcángel Miguel asegura que la clave para una buena salud es enfocarse en el bienestar en lugar de las enfermedades o heridas. Se te recomienda mantenerte centrado en tus deseos, no en tus miedos. El cuerpo reacciona instantáneamente al amor y a los miedos, elige el primero. Llena cada célula de bendiciones y afecto. Visualiza y espera salud completa para ti y los demás. Habla de ti y de los demás en términos de salud perfecta, afirmando que todo está bien.  Posibles significados: Notarás una mejoría en tu salud. Sigue tus instintos acerca de la salud y la sanación. Tu misión de vida incluye sanación. Haz cambios positivos en tu estilo de vida. Utiliza frases positivas, especialmente acerca de la salud. Busaca una segunda opinión médica. Oración: Dios y Arcángel Miguel, gracias por recordarme constantemente que debo enfocarme en una salud perfecta, y por encauzar mis acciones hacia mi bienestar." },
{ phrase:
  "'13. Es momento de abandonar esta situación malsana' El Arcángel Miguel ha escuchado tus suplicas y te responde: ¡Vete! Has durado demasiado en una situación tóxica, invirtiendo tiempo y energía que no te lleva a ningún resultado. Esta experiencia no te beneficia ni a ti ni a los involucrados. No necesitas mantener esta negatividad, aléjate sin dudas ni culpas. Los Ángeles te ayudarán asegurando que la partida sea lo más armoniosa posible, y el Arcángel Miguel te protegerá. Sigue tu intuición a cada paso y la transición será tranquila. Posibles significados: Busca un nuevo trabajo. Desintoxícate del alcohol, cigarros u otras drogas. Busca un consejero en relaciones. Habla claramente con quién tienes diferencias. Realiza una dieta más saludable. Pide una segunda opinión médica. Consulta un abogado de divorcio. Cámbiate de casa. Asegúrate de que el ambiente que te rodea está libre de químicos y toxinas. Oración: Arcángel Miguel, ¿en qué áreas de mi vida necesito enfocarme en este momento? Gracias por ayudarme a escuchar tus respuestas y por darme el valor para realizar cambios saludables en mi vida. " },
{ phrase:
  "'14. Escribe acerca de tus pensamientos y sentimientos' Estás confundido por sentimientos encontrados, y no sabes qué dirección tomar. El Arcángel Miguel te ayudará a profundizar en tus sentimientos, removiendo capas para así llegar al núcleo de la verdad. Él te aconseja que escribas todo sentimiento y pensamiento –sin editar ni censurar tus palabras. Mantener un diario privado te ayudará a tener mejor percepción de la naturaleza de aquello que realmente deseas. Esta claridad iluminará los pasos que debes seguir. Posibles significados: Escribe ya sea como hobby o profesionalmente. Toma cursos de redacción. Escribir es parte de tu misión divina. Aprende un nuevo idioma. Únete a un grupo de escritores. Envía tus escritos a un editor o a alguna revista. Oración: Gracias por ayudarme a encontrar mi creatividad nata y mi sabiduría, para así poder expresarme, expandir mivisión, bendiciones y sanación. " },
{ phrase:
  "'15. Estás en el camino correcto' Tus pensamientos y acciones van en la dirección correcta para llegar a tu misión de vida y la paz interior y los Ángeles celebran que la sigas fielmente. Aunque el futuro no esté aún muy claro los Ángeles quieren que sepas que te protegerán y guiarán a cada paso del camino. Sigue trabajando.  Posibles significados: Es tiempo de iniciar un nuevo proyecto: inicia un negocio, lee un libro, o haz un cambio saludable en tu forma de vida. Escucha tu guía interna aun cuando los demás no lo comprendan. Confía que estarás apoyando económicamente mientras sigues adelante con tus planes. Oración: Arcángel Miguel te pido tu presencia. Gracias por guiarme claramente, por motivarme y darme el valor y la confianza para realizar los cambios saludables en mi vida." },
{ phrase:
  "'16. Éste es tu propósito de vida' El Arcángel Miguel ha escuchado tus oraciones, y te guía hacia el camino para el cual naciste. Ya tienes ideas acerca de la carrera que te traerá alegrías, emociones, oportunidades de ayudar y seguridad financiera; y estas ideas son indicadores de tu misión divina. Estás hecho para comprometerte en actividades que te hagan feliz a ti y a los demás.  Esta respuesta es la confirmación de que la carrera con la que has soñado es tu misión de vida, por lo cual el universo te apoyará y abrirá puertas. Avanza con confianza. Posibles significados: Tu situación actual te ofrece pistas acerca de los siguientes pasos en tu camino –sigue tus sentimientos. Los ángeles vigilan tu negocio y tus finanzas. Oración: Arcángel Miguel, conoces los detalles de mi misión divina, y te pido me ayudes a alinearme con mis metas. Guía mis acciones para tomar los pasos correctos y así manifestar mi maravillosa y valiosa carrera." },
{ phrase:
  "'17. Honra y confía en tus sentimientos' El Arcángel Miguel te invita a buscar en tu interior y escuchar, esta respuesta es una señal de que tus sentimientos van de acuerdo a la verdad. Algunos de éstos serán difíciles de enfrentar, pero están ahí por alguna razón específica. Si tienes preocupaciones, siéntate, toma una pluma, un papel y ‘’entrevístate’’, pregúntate ¿qué sientes? ¿Porqué? ¿Qué te gustaría hacer? Tus sentimientos responderán claramente siempre y cuando mantengas una mente abierta y confías en lo que escuchas. Respeta tu llamada interior como esa poderosa fuerza que te conecta con la divinidad. Algunas veces Dios y los ángeles responden y guían por medio de los sentimientos físicos y emocionales. Si dices ‘’Es sólo un presentimiento’’ estás ignorando la ayuda divina. Escucha tus sentimientos. Posibles significados: Es tiempo de aceptar lo infeliz que te hace esa situación y tomar las medidas necesarias para corregirlo. Alguien intenta cambiar tus sentimientos, apégate a lo que sientes y sabes. Oración: Gracias Arcángel Miguel por apoyarme, guiarme y protegerme mientras escucho y actúo de acuerdo a mis sentimientos. Ayúdame a entender y expresar mis sentimientos con amor." },
{ phrase:
  "'18. Inocencia' El Arcángel Miguel te sostiene en sus brazos amorosamente confirmando tu inocencia. Pídele que te ayude a perdonarte y liberarte de culpas (pesadas emociones que evitan que sientas paz interior) diciendo: ‘’Arcángel Miguel gracias por ayudarme a perdonarme por (situación a perdonar) y por todo aquello por lo que me he culpado. Ayúdame a liberar mi cuerpo, mi mente y mis emociones de toda culpa. ’’ Siente la sensación de profunda liberación mientras el Arcángel Miguel te ayuda a abrazar tu verdadera inocencia. Tu comportamiento del pasado nunca deshará el trabajo perfecto de Dios, al crearte como un ser poderoso, cariñoso y pleno de luz y amor. Posibles significados: La persona por quién preguntas es inocente. Purifícate y desintoxícate. Puedes confiar en la situación por la que preguntas. Enfócate en las cualidades de los demás y no en sus errores. Oración: Dios y Ángeles, gracias por ayudarme a ver que todas sus cualidades de amor puro y luz se reflejan en mí y en los demás. Ayúdame a abrazar mi inocencia para estar en paz " },
{ phrase:
  "'19. Libérate del miedo ahora' El Arcángel Miguel asegura que el miedo es lo único que se interpone entre tú, tus planes y tu felicidad y quiere enseñarte como liberarte de cualquier preocupación o miedo para que te sientas seguro y a salvo. Te asegura que estás listo para liberarte del control de las cosas teniendo confianza en que todo se resolverá positivamente. Posibles significados: Vas en la dirección correcta. Te mereces todo lo bueno (¡Al igual que todos!). Permítete recibir amor, apoyo y abundancia. Eres amoroso. Oración: Arcángel Miguel ayúdame a sentirme seguro y merecedor de tus consejos. Gracias por liberarme de sentimientos y pensamientos tóxicos egocéntricos y pesados." },
{ phrase:
  "'20. Nuevos principios y un fresco inicio' Cuando un capítulo de tu vida se cierra otro comienza a florecer, en este momento quizá solo veas los primeros destellos de este comienzo, por lo que el Arcángel Miguel te da este mensaje para ayudarte a seguir adelante. ¡Hay una gran sorpresa esperándote! Mantén la fe y un pensamiento positivo. Posibles significados: La sanación es inminente. Experimentarás mejores condiciones en tu trabajo, o un nuevo trabajo. Los errores del pasado están perdonados y olvidados. Una mejoría en tu relación es evidente. Nace una nueva relación. Puede venir un cambio de casa. Un cambio en tu forma de pensar traerá felicidad y confianza. Deja atrás el pasado. Despeja y limpia tu casa a fondo. Oración: Gracias por traer nuevas oportunidades, por darme tu apoyo, por ayudarme a liberar y sanar mi pasado. Lléname de confianza mientras experimento cambios en mi vida." },
{ phrase:
  "'21. Pasa más tiempo al aire libre' El Arcángel Miguel te manda este mensaje, pidiéndote que salgas y establezcas contacto con la naturaleza, el aire fresco te ayudará a escuchar la voz divina más fácil y claramente, y el paisaje relajará y aliviará tu cuerpo y mente. Todos estos factores reducen el estrés y las preocupaciones, lo cual te permitirá atraer y manifestar en niveles superiores. ¡Piensa en las salidas como una inversión que paga altos dividendos en todos los sentidos! Posibles significados: Emprende un viaje espiritual a un lugar de gran energía. Adopta un pasatiempo al aire libre. Ve a escalar o acampar. Practica la fotografía en la naturaleza. Asegúrate de que tu casa propicie un ambiente en armonía. Adquiere plantas para tu casa u oficina. Tu propósito de vida incluye la protección del medio ambiente o cuestiones relacionadas con los derechos de los animales. Abre tus ventanas, permitiendo la entrada de aire fresco a tu casa y oficina. Oración: Gracias por motivarme a pasar más tiempo al aire libre, y por ayudarme a relajarme y disfrutar mi conexión con la naturaleza. " },
{ phrase:
  "'22. Pensamientos positivos generan resultados positivos' Esta situación requiere pensamientos positivos, ingrediente mágico que has estado buscando, aunque alegues que ya tienes una mente positiva, el Arcángel Miguel te aconseja que limpies tus palabras y pensamientos de todo negatividad o preocupaciones que pudieran disminuir su capacidad de manifestación. Miguel asegura que puedes saber que tan constructivos son tus pensamientos al poner atención a los recientes eventos en tu vida, ya que existe una correlación entre resultados y pensamientos positivos. Él te ayudará a animar tu espíritu para que tus experiencias sean bienvenidas y felices. Posibles significados: Practica tus afirmaciones diariamente (o cada hora). Lee un libro o toma clases de pensamiento positivo. Evita culparte a ti o a los demás –enfócate en las soluciones. En vez de preocuparte, ora y practica un estado mental amoroso y compasivo. Oración: Sabiduría y amor divinos yo os invoco, sé que mi mente y mis sentimientos están continua y eternamente conectados con ustedes, pido a mi ser superior se dé cuenta y esté consciente del amor y la luz que brilla en cada una de las personas y situaciones." },
{ phrase:
  "'23. Perdónate: No has hecho nada malo     ' El Arcángel Miguel ve que la culpa interfiere en tu búsqueda de la felicidad. Te estás culpando por algo del pasado, es tiempo de soltarlo, ya que la culpa no es productiva y enferma. No has hecho nada malo, en el momento hiciste tu mejor esfuerzo.  Posibles significados: Piensa y exprésate positivamente sobre ti mismo. Deja de darle vueltas al pasado. Envía tus bendiciones a aquellos con los que estás enojado como señal de sanación tuya y de la situación. Recuerda que no es posible controlar los sentimientos y reacciones de los demás. Intégrate en grupos de apoyo. Oración Pido que me ayudes a soltar todas mis culpas y a perdonarme. Por favor aconséjame mientras libero todo enojo y miedo hacia los demás. Gracias Arcángel Miguel por permitirme sentirme centrado y en paz." },
{ phrase:
  "'24. La persona en cuestión es confiable' Puedes confiar en la persona involucrada en esta situación (así como confiar en ti). Todos cometemos errores o actuamos egoístamente de vez en cuando, pero puedes confiar en la persona que estás pensando. A él o ella le importas y actuará amorosamente. El Arcángel Miguel te aconseja no esperar la perfección de una persona ya que esto tensiona las relaciones, trata a los demás como a ti te gustaría ser tratado: Con amor y compasión. Posibles significados: Tus ideas son válidas y dignas de confianza. La persona que acabas de conocer se convertirá en una pareja romántica. Cree en lo que esta persona te dice aunque no te guste. Este individuo será un gran socio de negocios. Deja de culpar a los demás y entrega tu enojo y resentimientos a los Ángeles para que sanes. Oración: Gracias por ayudarme a tener fe en mis relaciones para abrir más mi corazón, agradezco su protección al tener solamente personas dignas de confianza en mi vida." },
{ phrase:
  "'25. Presta atención a tus sueños' El Arcángel Miguel trabajo contigo en tus sueños ayudándote a liberar viejos miedos y alcanzar nuevos niveles de felicidad y paz. Te ha estado enseñando mientras duermes, proporcionándote repuestas a tus peticiones y construyendo los cimientos de la misión de tu vida. Aunque puede ser que no recuerdes estos sueños, la información está en ti y te ayuda de varias maneras. Podrías acceder a los consejos de Miguel llevando un diario de tus sueños, cualquier cuaderno servirá; mantenlo junto a tu cama y anota constantemente cualquier detalle que recuerdes haber soñado la noche anterior. Pronto verás y reconocerás patrones en temas y símbolos que te ofrecerán guía en tus horas de vigilia. Posibles significados: Los sueños recurrentes hablan, asegúrate de prestarles atención. Respeta y actúa de acuerdo a los deseos de tu corazón. Consulta a un experto en sueños o algún libro sobre el tema. Asegúrate de dormir lo suficiente. Ve a la cama sobrio ya que los químicos interrumpen los sueños. Oración: Gracias por arroparme por las noches y ayudarme a disfrutar una noche de sueño maravillosamente descansado. Arcángel Miguel, te invito a formar parte de mis sueños como maestro, guía y sanador. Ayúdame a entender (Describe la situación) en un nivel espiritual y aconséjame." },
{ phrase:
  "'26. Protégete' Este mensaje indica que eres particularmente sensible a las energías y emociones en este momento. El Arcángel Miguel te protege de las energías ásperas, pero también es necesario que tú tomes acciones en este esfuerzo. Por ejemplo, evita situaciones que expresen coraje y/o competitividad. Aléjate de los bares, pubs u otros lugares en donde se abuse de sustancias químicas ya que puedes atraer más energía de baja vibración. Mantén tus hábitos naturales, como conocerte a ti mismo y pasar más tiempo con personas gentiles. Posibles significados: Lleva un cristal protector, como lo obsidiana negra. Asegúrate de estar físicamente protegido, esto incluye tener actualizada tu póliza de seguro, que tu automóvil esté en buenas condiciones, etcétera. Sé precavido al tratar esta situación o relación. Oración: Arcángel Miguel, te pido me protejas a mí y a mis seres queridos, mi automóvil, y mi hogar con tu escudo poderoso. Rodéanos con tu luz azul, que solo da paso al amor puro. Acompáñame día y noche y mantén a salvo a mis seres queridos. (Nombra situaciones y/o personas)." },
{ phrase:
  "'27. Reconoce y actúa de acuerdo a la verdad' Has recibido este mensaje debido a que existe un sentimiento importante que tratas de ignorar. Por más que trates de ignorarlo, éste te pide que seas honesto contigo. El Arcángel Miguel afirma que el enfrentamiento con la verdad será reconfortante, y te dará la claridad y dirección que buscas. Has intentado ignorar el llamado de tu interior por medio a los cambios que esto puede traer a tu vida. El Arcángel Miguel confirma que sigue guiándote y asegurándose de que tus necesidades estarán satisfechas y tus relaciones se mantendrán sanas.  Posibles significados: Sana o aléjate de situaciones enfermizas. No te comprometas. Enfrenta tus miedos. Mantén pensamientos de amor acerca de ti y la situación por la cual preguntaste. Oración: Agradezco tu apoyo al ayudarme a enfrentar mis sentimientos con gracias y aceptación para ser amorosamente honesto conmigo y los demás. Gracias Arcángel Miguel por otorgarme el valor y la fuerza. " },
{ phrase:
  "'28. Respétate ' El Arcángel Miguel te apoya en la búsqueda de la felicidad, la salud y la abundancia, aconsejándote que te respetes y te ames. La situación por la que preguntas cuenta con algunos aspectos disfuncionales, que pueden afectar tu autoestima. Este mensaje es la señal de que es momento de honrarte como persona aún cuando los demás no te traten como te mereces. Mereces respeto de ti y de los demás, como hijo amado de Dios.  Posibles significados: Busca terapia para reforzar tu auto-estima. Abandona la situación abusiva. Libérate de comportamientos que sabes son negativos para ti, tales como la culpa, que erosiona el respeto propio. Insiste en que todos te respeten. Oración: Dios y Ángeles, gracias por ayudarme a verme como ustedes me ven, a través de los ojos del amor. Gracias por honrarme y respetarme –guíenme para hacerlo de la misma manera, y otórguenme el valor para defenderme. Pido su protección en todas mis relaciones para estar rodeado de gente cariñosa y generosa." },
{ phrase:
  "'29. Rezar ayudará esta situación' El Arcángel Miguel te recuerda que orar mejora cualquier situación, mientras las preocupaciones hacen lo contrario. Orar ayuda porque permite a Dios y a los ángeles ofrecer su ayuda ya que no pueden violar el libre albedrío. Solo interceden con tu autorización y si lo pides, siendo éste el objetivo de una oración. Aún cuando tus oraciones pueden ser respondidas en una manera diferente a la esperada, descansa, seguro de que estás siendo escuchado. La mente divina sabe la solución perfecta para todos los involucrados, por lo que tu papel es solo pedir ayuda y seguir los consejos como te sean dados. Dios y los Ángeles están a cargo de cómo las oraciones son respondida, que usualmente es de una forma ingeniosa y fuera del alcance dela imaginación humana.  Posibles significados: Busca un grupo de oración –mientras más oradores, mejor! Otorga tus preocupacionesy miedos a Dios y los Ángeles. Ten fe, existen razones para tener esperanza. Ábrete a la posibilidad de soluciones distintas a las que esperas. Oración: Dios, Arcángel Miguel (y a quien quieras rezarle) pido su intervención divina (describe la situación). Agradezco su ayuda, sigo y confío en su guía con gratitud y gracia. Necesito un milagro y pido me sea enviado pronto. Gracias, Amén. " },
{ phrase:
  "'30. Sé gentil contigo' El Arcángel Miguel te guía a honrar tu sensibilidad física y emocional. Te exiges demasiado y te castigas por las imperfecciones en tu mente. Date una oportunidad, baja el ritmo y sé bueno contigo mismo.  Posibles significados: Aléjate de la relación o situación conflictiva. Cambia tu dieta por una más saludable. Evita químicos en alimentos y en el ambiente. Duerme más. Cambia tu rutina de ejercicio por una más ligera. Habla cariñosamente de ti y los demás. Necesitas tiempo en silencio. Oración: Arcángel Miguel, por favor ayúdame a tratarme con gentileza, a nutrir de amor todas mis acciones, mis pensamientos y mis palabras. Ayúdame a estar seguro de merecer compasión. Te entrego todo sentimiento de culpa para así poder experimentar una paz interior duradera." },
{ phrase:
  "'31. Sentido del humor' Esta situación se beneficiaría con sentido del humor. Observa tus experiencias como si estuvieras viendo la escena de una película, teniendo siempre en cuenta –como dijo Shakespeare – que ‘’El mundo es un escenario’’. ¿Qué encuentras gracioso acerca de la naturaleza humana en esta situación? Obteniendo una nueva perspectiva acerca del comportamiento de los demás, puede automáticamente desengancharte con amor. El humor permite a la gente bajar la guardia y permitir que el amor entre y sane las situaciones y relaciones, es por eso que Dios y los Ángeles tienen un excelente sentido del humor… Y tú también! Posibles significados: Reconoce que la risa es la mejor medicina. Ve una película o un show de comedia para alegrarte el ánimo. Tu proyecto de vida podría incluir escribir, actuar o recitar comedia. Aprende nuevos chistes como una forma de ayuda en tus relaciones. Inscríbete en una clase de comediantes para mejorar tu confianza y dicción. Oración: Gracias por ayudarme a ver esta situación con humor para así poderme reír de la naturaleza humana. Estoy dispuesto a ver mi experiencia desde otro punto de vista para así atraer amor y energía sanadora." },
{ phrase:
  "'32. Sigue adelante sin miedo' Este mensaje es una señal de que vas en el camino correcto, y es seguro seguir adelante con tus planes. Mientras tus intenciones estén enfocadas en los deseos de tu corazón, tus pasos serán posicionados automáticamente en la dirección correcta. En este momento es importante que actúes –sin importar lo pequeño- hacia el resultado que deseas. Pide al Arcángel Miguel te aconseje diciendo ‘’Por favor muéstrame cual es el siguiente paso’’ y el vendrá en tu auxilio, brindándote protección y ayuda durante los cambios significativos. Posibles significados: Estás apoyado durante los cambios en tu vida. Abandona una situación malsana. Es buen momento para iniciar un nuevo negocio o sociedad. Inicia esta relación con la mente y el corazón abiertos. Esta es la elección correcta. Oración: Gracias por caminar junto a mí a cada paso, por llevarme de la mano, darme confianza y valor, y por guiar mis pensamientos y acciones en dirección del amor y mi verdadero propósito de vida. " },
{ phrase:
  "'33. La situación ya está resuelta. Arcángel Miguel te asegura que la situación por la que preguntas ha concluido gratamente. Los Ángeles han trabajado tras bambalinas para sanar el origen de tus preocupaciones. Aunque todavía no veas la resolución cree en ésta. Deja de lado las preocupaciones y relájate seguro de que todo está bien.' Posibles significados: No hay nada de qué preocuparse. Todo resultará de acuerdo a lo planeado. Vale la pena salvar esta relación. Quédate donde estás, los problemas se resolverán pronto. Oración: Te entrego todas mis preocupaciones, ocupaciones e inquietudes a cambio de paz en todos los sentidos. Gracias por resolver (Describe la situación) de una manera divina." },
{ phrase:
  "'34. Solicita la ayuda del Arcángel Miguel.' La situación que te preocupa mejorará con la ayuda del Arcángel Miguel. Nunca es demasiado tarde para involucrar a los Ángeles, y su ayuda mejorará todo inmediatamente… Te dará paz interior, nuevas ideas y puntos de vista. Miguel te ayudará de formas inesperadas así como ingeniosas, mantente abierto a milagros que toman formas sorpresivas. Posibles significados: Eres poderoso -no eres una víctima. Libérate y libera a los demás de culpas. Enfócate en soluciones, no en problemas. Permite que los demás te ayuden. Mantén tu mente abierta a soluciones alternativas. Oración: Arcángel Miguel, gracias por tu ayuda con (Tu situación, pregunta etc.). Por favor ayúdame a llenarme de paz y fe, siempre." },
{ phrase:
  "'35. Ten confianza' Este mensaje funciona como talismán para incrementar la confianza en uno mismo. El Arcángel Miguel ha tratado de asegurarte que cuentas con la fuerza, el poder y las habilidades valiosas para el plan de paz de Dios. Miguel te protege mientras brillas con luz propia. Escucha tu intuición y actúa con aplomo. En tus relaciones, tu confianza atraerá a tu lado a gente sana, generando respeto en los demás. Antes de dormir por las noches pídela al Arcángel Miguel su ayuda para incrementar tu confianza. Despertarás sintiendo amor y compasión por ti y por los demás.  Posibles significados: Confía en tus planes e ideas. Sintonízate con tu intuición, estás alineado con tu objetivo. Confía en la persona por la que preguntaste. Ten fe en que vas por el camino correcto. Confía en que tus necesidades financieras y demás están cubiertas ahora y en el futuro. Oración: Arcángel Miguel, préstame tu valor y fortaleza. Ayúdame a aceptar que soy Uno con todo lo que es divino: sabiduría, fuerza, amor, creatividad, abundancia y salud. Permíteme sentir paz y confianza en todos los sentidos." },
{ phrase:
  "'36. Tómate tu tiempo para decidir' Has estado preguntando sobre una situación donde existe confusión o indecisión, y este mensaje es la señal de que no debes apresurar las cosas. Más información te será revelada con el paso del tiempo, la cual guiará tus acciones de forma natural. No hay necesidad de forzar nada en este momento, la oportunidad no se irá si no la notas inmediatamente, y los demás tendrán paciencia. Es tu decisión y el mejor camino a seguir es ir más despacio y tomarte tu tiempo. Posibles significados: No firmes el contrato todavía, negocia algo mejor. Baja el ritmo de tu nueva relación. Pregunta más antes de dar el sí. Investigatus opciones y alternativas. No te dejes presionar por los demás ya que sólo buscan su beneficio. Oración: Arcángel Miguel ayúdame a mantenerme fuerte y relajado mientras enfrento esta situación. Recuérdame desengancharme y dar un paso atrás permitiendo a la situación desenvolverse naturalmente. Gracias por tu protección." },
{ phrase:
  "'37. Trabajo de sanación energética ' Tu situación actual mejoraría con una sanación energética que puedes solicitar de los Ángeles (¡Sólo pídelo!), un sanador energético capacitado o tus propias intenciones y energía. Posibles significados: Toma las medidas necesarias para encauzar tu energía y vitalidad, tales como: ejercicio, y dietas balanceadas. Inscríbete en un curso de sanación energética. Concreta una sesión con un sanador energético. En tu misión de vida está el trabajo de sanador energético. Oración: Gracias por enviar energía sanadora a mí y a través de mí, para mi propio bien y el de aquellos que me rodean. Gracias por conectarme con maestros y sanadores de energía íntegra y cariñosa." },
{ phrase:
  "'38. Tú creaste esta situación y tienes el poder de cambiarla' Te recuerda que eres un creador poderoso, hecho a imagen y semejanza del Divino Creador, no eres una víctima pasiva; tienes el derecho y las habilidades para sobresalir y cambiar cualquier cosa en esta situación o relación. Sin embargo, mientras más culpes a los demás o creas que ellos te controlan, seguirás atrapado. Pero invocando a Dios y al Arcángel Miguel, y haciéndote cargo de acuerdo a su guía, puede cambiar todo de forma milagrosa.  Posibles significados: Libérate y libera a los demás de culpas. Escribe una lista de pasos a seguir, y realiza uno o más al día. Ten una conversación honesta con las personas involucradas en esta situación. Toma uno o varios pasos para convertir tus sueños en realidad. Permítete hacer cambios saludables en tu vida. Oración: Gracias por dejarme recargarme en tu fuerza y recordarme mi propio poder personal. Por favor guíame hacia la manifestación y sanación de acuerdo con la voluntad divina, creando paz y bendiciones para todos los involucrados." },
{ phrase:
  "'39. Tu hogar está protegido por los Ángeles' Tienes preguntas o sentimientos vulnerables con respecto a tu hogar o forma de vida, pero el Arcángel Miguel te asegura que todo está bien. Los Ángeles protegen tu actual residencia, asegurándola física y económicamente. Si te vas a mudar, ésta es la señal de su ayuda con el cambio. Relájate y disfruta de tu hogar porque todo está bien.  Posibles significados: Los Ángeles cuidan de tu hogar, tus seres queridos y tus pertenencias mientras viajas. Los Ángeles te ayudarán a encontrar aquello que tienes perdido. Las peticiones sobre tu casa fueron escuchadas y respondidas. Ganancias inesperadas te ayudan a pagar tu renta o hipoteca. Los Ángeles te guían hacia un hogar costeable y maravilloso, confía y haz caso a tu guía interior. Oración: Arcángel Miguel, gracias por cuidar mi casa y a sus habitaciones. Te pido pongas a tus Ángeles guardianes en cada puerta y ventana, asegurando su seguridad. Gracias por guiar mis finanzas para poder costear fácilmente mi renta, hipoteca o impuestos." },
{ phrase:
  "'40. Tu intuición es real y confiable' El Arcángel Miguel sabe que te sientes inseguro o confundido, por lo que te manda este mensaje como confirmación de que lo estas escuchando correctamente por medio de tus ideas, sentimientos y pensamientos. Recientemente has sentido la necesidad de tomar acciones pero la posibilidad de equivocarte te hace dudar. Te confirma que es seguro seguir adelante con estos cambios.  Posibles significados: Tu nueva idea es la respuesta, así que actúa. Los sentimientos que experimentas son válidos. Sino confías en esa persona o situación, presta atención a ese sentimiento. Estás siendo guiado por tu interior, aunque no puedas ver hacia donde te lleva hazle caso. Oración: Ayúdame a ver, escuchar, sentir y conocer claramente el consejo divino que he pedido, permíteme liberarme de mi ego para que el caudal de tu sabiduría llegue a mí… para mi beneficio y el de los demás." },
{ phrase:
  "'41. Tú y tus seres queridos están a salvo' El Arcángel Miguel y otros Ángeles te protegen a ti y a tus seres queridos… incluyendo a tu familia y amigos del cielo. EAhora tienes la señal de que te puedes relajar, sabiendo que el Arcángel se está haciendo cargo de los detalles y salvaguardándote a ti y a los tuyos de todas las maneras. Posibles significados: Entrega tus preocupaciones a Dios y los Ángeles. Tus necesidades económicas están cubiertas. Es seguro viajar. Un ser querido en el cielo está feliz y te envía su amor. Recuerda que las preocupaciones son una forma de pedir, así que sólo pide por aquello que en verdad deseas. Oración: Dios y Arcángel Miguel, gracias por cuidar de mí y de mis seres queridos (Nombres). Ayúdame a sentirme seguro y en paz; llénamede fe para poder enfocarme en mis prioridades y disfrutar de una vida feliz y saludable." },
{ phrase:
  "'42. Tus hijos están siendo cuidados por los Ángeles' El Arcángel Miguel quiere que sepas que está prestando especial atención a tus hijos. Los guía para estar a salvo, a desarrollar sus dones espirituales, y a descubrir y seguir su propósito divino de vida. Miguel también se asegura de que sus semejantes sean dignos de confianza y buena influencia. Posibles significados: Tu misión de vida tiene que ver con niños. Un embarazo y parto saludables están asegurados. La adopción será exitosa. Pasa más tiempo con niños Índigo y Cristal. Ocúpate de tu niño interior, jugando y divirtiéndote. Un niño en el cielo está feliz y te envía su amor. Tus hijos están bien. Entrega tus preocupaciones sobre tus hijos a Dios y los Ángeles. Oración: Ángeles guardianes de mis hijos (nacidos y por nacer), gracias por cuidarlos y asegurar su felicidad y seguridad. Guíenme para poder elegir la mejor manera de ser un buen padre y un modelo ejemplar para mis hijos y los de los demás." },
{ phrase:
  "'43. Un resultado favorable' La situación que te preocupa fue resuelta de una forma justa, Tú (y todos los involucrados), estarán conformes con el resultado. La ingenuidad celestial ha desarrollado un plan que sobrepasa la imaginación humana. Podrás no ver la solución inmediatamente pero ten confianza que ya está hecha. Se te aconseja entregar tus preocupaciones y resentimientos al Arcángel Miguel ya que no hay necesidad de que cargues con ellos. Mientras más cargas liberes a Dios, más rápido se manifestará el resultado favorable.  Posibles significados: Una situación legal se resolverá a tu favor. Tu nueva relación será de larga duración. Te darán el empleo que deseas. El dinero vendrá. Una sanación se llevará acabo. Oración: Gracias por el hermoso resultado de esta situación, el cual es justo y perfecto para todos los involucrados. Gracias Arcángel Miguel por ayudarme a confiar y a tener fe." } ]

  function shuffle(a) {
    var j, x, i;
    for (i = a.length - 1; i > 0; i--) {
        j = Math.floor(Math.random() * (i + 1));
        x = a[i];
        a[i] = a[j];
        a[j] = x;
    }
}

shuffle(frases);

var myDoc = app.activeDocument;

app.findTextPreferences = NothingEnum.nothing;
app.changeTextPreferences = NothingEnum.nothing;
app.findChangeTextOptions.caseSensitive = true;
app.findChangeTextOptions.includeFootnotes = false;
app.findChangeTextOptions.includeHiddenLayers = false;
app.findChangeTextOptions.includeLockedLayersForFind = false;
app.findChangeTextOptions.includeLockedStoriesForFind = false;
app.findChangeTextOptions.includeMasterPages = false;
app.findChangeTextOptions.wholeWord = true;

for (i = 1; i <= 13; i++) {

  $.writeln (frases[i].phrase)
  app.findTextPreferences.findWhat = "FMIK"+i;
  app.changeTextPreferences.changeTo = frases[i-1].phrase;
  myDoc.changeText();
  
  }

app.findTextPreferences = NothingEnum.nothing;
app.changeTextPreferences = NothingEnum.nothing;